"""Build the App Service code package: one zip with the API, the agent definitions and the built UI.

    python scripts/build_package.py                     # npm ci + build, then zip -> .local/crip-app.zip
    python scripts/build_package.py --skip-ui-build     # reuse frontend/dist
    python scripts/build_package.py --out path/to/app.zip

The zip keeps the repository layout, so the app finds its UI and agent
definitions with its default settings (no path app settings needed):

    requirements.txt            generated from backend/pyproject.toml; App Service's build (Oryx) installs it
    backend/crip_backend/...    the FastAPI app (started with uvicorn --app-dir backend)
    foundry/definitions/...     agent definitions (registered in Foundry at startup)
    frontend/dist/...           the built React UI

No secrets are packaged: .env, .secrets and local databases are never included.
Standard library only, so it runs on any agent with Python 3.11+ (Windows or Linux).
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tomllib
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKIP_DIRS = {"__pycache__", ".pytest_cache", "node_modules"}
SKIP_SUFFIXES = {".pyc", ".pyo", ".db", ".sqlite"}


def run(cmd: list[str], cwd: Path) -> None:
    exe = shutil.which(cmd[0])  # resolves npm.cmd on Windows
    if exe is None:
        sys.exit(f"'{cmd[0]}' was not found on PATH (Node.js 20.19+/22 is needed to build the UI)")
    print(f"$ {' '.join(cmd)}  (in {cwd.relative_to(ROOT)})", flush=True)
    subprocess.run([exe, *cmd[1:]], cwd=cwd, check=True)


def requirements() -> str:
    project = tomllib.loads((ROOT / "backend" / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    deps = project["dependencies"]
    return "# Generated by scripts/build_package.py from backend/pyproject.toml. Do not edit.\n" + "\n".join(deps) + "\n"


def files_under(base: Path) -> list[Path]:
    out = []
    for path in sorted(base.rglob("*")):
        rel = path.relative_to(base)
        if path.is_file() and not (set(rel.parts) & SKIP_DIRS) and path.suffix not in SKIP_SUFFIXES:
            out.append(path)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--out", type=Path, default=ROOT / ".local" / "crip-app.zip")
    parser.add_argument("--skip-ui-build", action="store_true", help="reuse an existing frontend/dist")
    args = parser.parse_args(argv)

    frontend = ROOT / "frontend"
    if not args.skip_ui_build:
        run(["npm", "ci", "--no-audit", "--no-fund"], frontend)
        run(["npm", "run", "build"], frontend)
    if not (frontend / "dist" / "index.html").is_file():
        sys.exit("frontend/dist/index.html is missing: build the UI first (drop --skip-ui-build)")

    content = {
        "backend/crip_backend": ROOT / "backend" / "crip_backend",
        "foundry/definitions": ROOT / "foundry" / "definitions",
        "frontend/dist": frontend / "dist",
    }
    out = args.out.resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    count = 0
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("requirements.txt", requirements())
        zf.write(ROOT / "backend" / "pyproject.toml", "backend/pyproject.toml")
        for prefix, base in content.items():
            for path in files_under(base):
                # POSIX separators: a zip built on Windows must unpack correctly on Linux.
                zf.write(path, f"{prefix}/{path.relative_to(base).as_posix()}")
                count += 1
    print(f"Package: {out} ({out.stat().st_size / 1_048_576:.1f} MB, {count + 2} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
